<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Delgato-72cb2703-0f46-4a91-a168-b06c5cebc715</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Delgato.Core\Delgato.Core.csproj" />
      <ProjectReference Include="..\Delgato.Configuration\Delgato.Configuration.csproj" />
      <ProjectReference Include="..\Delgato.Agents\Delgato.Agents.csproj" />
      <ProjectReference Include="..\Delgato.Orchestration\Delgato.Orchestration.csproj" />
      <ProjectReference Include="..\Delgato.Transports\Delgato.Transports.csproj" />
    </ItemGroup>
</Project>
